/*
 * 389. Find the Difference
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 */

#include <string>
using namespace std;

class Solution {
    public:
        char findTheDifference(string s, string t) {
            // Calculate difference
            //
            // int len = s.length();
            // char res = 0;
            // for (int i = 0; i < len; i++) {
            //     res += t[i] - s[i];
            // }
            // res += t[len];
            // return res;

            // xor
            int len = s.length();
            char res = t[len];
            for (int i = 0; i < len; i++) {
                res ^= (s[i] ^ t[i]);
            }
            return res;
        }
};
